# Pre-commit hooks
# See https://pre-commit.com for more information

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: ^(.*\.md|.*\.txt)$
      - id: end-of-file-fixer
        exclude: ^(.*\.md|.*\.txt)$
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=10240']
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: mixed-line-ending

default_language_version:
  python: python3
